version: "3.9"

services:
  db:
    image: postgis/postgis:16-3.4
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: poopmap
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  api:
    build: ./server
    restart: on-failure
    env_file: .env
    depends_on:
      - db
    ports:
      - "4000:4000"

  web:
    build: ./client
    restart: on-failure
    env_file: .env
    depends_on:
      - api
    ports:
      - "3000:80"

volumes:
  db-data:
